version: '3'
services:
  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ubaid
      - MONGO_INITDB_ROOT_PASSWORD=ubaid
    volumes:
      - mongo-db:/data/db
      
  redis:
    image: redis

  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
volumes:
  mongo-db: