version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node index.js
      
  nginx:
    ports:
      - "80:80"
    depends_on:
      - node-app
    environment:
        - NODE_ENV=production
  mongo-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

